# Generated by Django 4.2.3 on 2023-07-05 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollegeSubjects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject_code", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("branch", models.CharField(max_length=100)),
                ("year", models.IntegerField()),
                ("marks", models.IntegerField()),
                ("time", models.IntegerField()),
            ],
            options={
                "verbose_name_plural": "College Subjects",
            },
        ),
        migrations.CreateModel(
            name="Credentials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_id", models.CharField(max_length=10, unique=True)),
                ("password", models.CharField(max_length=15)),
            ],
            options={
                "verbose_name_plural": "Credentials",
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_id", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("branch", models.CharField(max_length=100)),
                (
                    "college",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.college"
                    ),
                ),
                ("subjects", models.ManyToManyField(to="home.collegesubjects")),
            ],
            options={
                "verbose_name_plural": "Student",
            },
        ),
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.collegesubjects",
                    ),
                ),
            ],
        ),
    ]
