# Generated by Django 4.2.3 on 2023-07-05 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_subjectspecificexam"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="subjects",
        ),
    ]
