# Generated by Django 4.2.3 on 2023-07-06 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_examrecord"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ExamRecord",
        ),
    ]
