# Generated by Django 4.2.3 on 2023-07-06 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_responsesrec"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examrecord",
            name="warningcount",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
