# Generated by Django 4.2.3 on 2023-07-06 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0010_alter_examrecord_warningcount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examrecord",
            name="image",
            field=models.ImageField(upload_to="media/exam_images/"),
        ),
    ]
