# Generated by Django 4.2.3 on 2023-07-06 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0013_aa"),
    ]

    operations = [
        migrations.DeleteModel(
            name="aa",
        ),
    ]
