# Generated by Django 4.2.3 on 2023-07-06 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0014_delete_aa"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ResponsesRec",
        ),
    ]
